// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsSM8tDZpzPXNQaNGsuhdJ18hAa-3iIU8',
    appId: '1:444310607170:web:910ae810f53682a852e4db',
    messagingSenderId: '444310607170',
    projectId: 'chatapp-eebb0',
    authDomain: 'chatapp-eebb0.firebaseapp.com',
    storageBucket: 'chatapp-eebb0.firebasestorage.app',
    measurementId: 'G-F5REJTX6PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTK9MSDNwNEDsKSGtLvyq8XzZNY1lyKIQ',
    appId: '1:444310607170:android:e2002e6819ab8f7a52e4db',
    messagingSenderId: '444310607170',
    projectId: 'chatapp-eebb0',
    storageBucket: 'chatapp-eebb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY8S2HWvcXuUAdIuYYpRCHeXYGa8fAWTI',
    appId: '1:444310607170:ios:bb0e4c32f713763352e4db',
    messagingSenderId: '444310607170',
    projectId: 'chatapp-eebb0',
    storageBucket: 'chatapp-eebb0.firebasestorage.app',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY8S2HWvcXuUAdIuYYpRCHeXYGa8fAWTI',
    appId: '1:444310607170:ios:bb0e4c32f713763352e4db',
    messagingSenderId: '444310607170',
    projectId: 'chatapp-eebb0',
    storageBucket: 'chatapp-eebb0.firebasestorage.app',
    iosBundleId: 'com.example.chattApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsSM8tDZpzPXNQaNGsuhdJ18hAa-3iIU8',
    appId: '1:444310607170:web:49cde56b5e4b1f8652e4db',
    messagingSenderId: '444310607170',
    projectId: 'chatapp-eebb0',
    authDomain: 'chatapp-eebb0.firebaseapp.com',
    storageBucket: 'chatapp-eebb0.firebasestorage.app',
    measurementId: 'G-C5K116SD7J',
  );
}
